---
abstract: 'turn on strict and make all warnings fatal'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: strictures
no_index:
  directory:
    - t
    - inc
recommends:
  bareword::filehandles: 0
  indirect: 0
  multidimensional: 0
requires:
  perl: 5.006
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=strictures
  repository: git://git.shadowcat.co.uk/p5sagit/strictures.git
version: 1.005000
